language: python
python: "2.7"

install:
  - pip install mock ddt nose ansible coverage coveralls

script:
  - nosetests --all-modules --with-coverage --cover-package library

after_success:
  - coveralls